riddles = ["David’s parents have three sons: Snap, Crackle, and what’s the name of the third son?",
           "I follow you all the time and copy your every move, but you can’t touch me or catch me. What am I?",
           "What has many keys but can’t open a single lock?",
           "What can you hold in your left hand but not in your right?",
           "What is black when it’s clean and white when it’s dirty?",
           "What gets bigger when more is taken away?",
           "I’m light as a feather, yet the strongest person can’t hold me for five minutes. What am I?",
           "I’m found in socks, scarves and mittens; and often in the paws of playful kittens. What am I?",
           "Where does today come before yesterday?",
           "What invention lets you look right through a wall?",
           "If you’ve got me, you want to share me; if you share me, you haven’t kept me. What am I?",
           "What goes up and down but doesn’t move?",
           "If you’re running in a race and you pass the person in second place, what place are you in?",
           "It belongs to you, but other people use it more than you do. What is it?"]

answers = ["david",
           "shadow",
           "piano",
           "right elbow",
           "chalkboard",
           "hole",
           "your breath",
           "yarn",
           "the dictionary",
           "window",
           "secret",
           "staircase",
           "second place",
           "your name"]

sentences = ['expel toxic people',
             'faster, harder, stronger',
             'feed the birds',
             'find a hobby',
             'pursue your passion',
             'focus and win',
             'follow your guts',
             'friends are treasures',
             'genius is patience',
             'get a massage',
             'get a pet',
             'get enough sleep',
             'get fresh air',
             'get over yourself',
             'give a compliment',
             'give more hugs',
             'give real value',
             'go for it',
             'god alone saves',
             'happiness is success',
             'have a mentor',
             'have a party',
             'health is wealth',
             'hearts can mend',
             'help a stranger']
